version: 2

updates:
  - package-ecosystem: "npm"
    directory: "source/web"
    schedule: 
      interval: "daily"
    commit-message: 
      prefix: "Yarn security update: "
    reviewers:
      - "octocat"
      - "guilhermedjr"
