version: "3.8"

services:
  wings: 
    image: peep_wings
    container_name: "wings"
    environment: 
      - PORT=5000
    ports: 
      - 5000:5000
    build: 
      context: .
      dockerfile: "../source/Wings/Peep.Wings/Peep.Wings.Application/Dockerfile"
      
  wings-postgres:
    image: postgres
    container_name: "wings-postgres"
    restart: always
    ports:
      - 4001:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=peepwingsdb
    volumes:
      - "/var/lib/postgresql/data"
    networks:
      - peep-network

  parrot-redis:
    image: redis:alpine
    container_name: "parrot-redis"
    restart: always
    command: "redis-server --requirepass redis-docker"
    ports:
      - 6379:6379
    volumes:
      - "./volumes/redis"
    networks:
      - peep-network

  # stork-postgres:
  #   image: postgres
  #   container_name: "stork-postgres"
  #   restart: always
  #   ports:
  #     - 4001:5432
  #   environment:
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_USER=root
  #     - POSTGRES_DB=peepstorkdb
  #   volumes:
  #     - "/var/lib/postgresql/data"
  #   networks:
  #     - peep-network

networks:
  peep-network:
    driver: bridge
